# Generated by Django 4.1 on 2022-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('LX', 'Linux'), ('AR', 'Arduino'), ('RB', 'RaspberryPI'), ('VI', 'VI and VIM')], default='LX', max_length=2),
        ),
    ]
