# Generated by Django 4.1 on 2022-08-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('LX', 'Linux'), ('AR', 'Arduino'), ('RB', 'RaspberryPI'), ('VI', 'VI and VIM'), ('PY', 'Python'), ('DJ', 'Django')], default='LX', max_length=2),
        ),
    ]
